local-address=0.0.0.0
local-port=5300
include-dir=/etc/powerdns/pdns.d
api=yes
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=127.0.0.1/32,172.16.0.0/12
cache-ttl=0
query-cache-ttl=0
loglevel=6
