local-address=0.0.0.0
local-port=53
allow-from=0.0.0.0/0,::/0
forward-zones=anyns.test=pdns-authoritative:5300
forward-zones-recurse=.=1.1.1.1;8.8.8.8
dnssec=validate
max-cache-entries=100000
quiet=no
loglevel=6
lua-dns-script=/etc/powerdns/recursor.lua
